# Generated by Django 4.2.20 on 2026-09-20 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('floor_no', models.PositiveIntegerField(default=0, verbose_name='Number of Floors')),
                ('land_area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Land Area (sqft)')),
                ('total_saleable_area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Saleable Area (sqft)')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_code'], name='projects_pr_project_0def5e_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=30)),
                ('floor_no', models.IntegerField()),
                ('flat_type', models.CharField(choices=[('STUDIO', 'Studio'), ('1BED', '1 Bedroom'), ('2BED', '2 Bedroom'), ('3BED', '3 Bedroom'), ('4BED', '4 Bedroom'), ('DUPLEX', 'Duplex'), ('PENTHOUSE', 'Penthouse'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='2BED', max_length=20)),
                ('facing', models.CharField(blank=True, max_length=50)),
                ('saleable_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saleable Area (sqft)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('HANDED_OVER', 'Handed Over')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'floor_no', 'flat_no'],
                'indexes': [models.Index(fields=['status'], name='projects_fl_status_6d92cb_idx')],
                'unique_together': {('project', 'flat_no')},
            },
        ),
    ]
