# Generated by Django 4.2.20 on 2026-09-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_flat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='features',
            field=models.CharField(blank=True, help_text='e.g. Drawing, Dining, Balcony', max_length=255, verbose_name='Rooms & features'),
        ),
        migrations.AddField(
            model_name='flat',
            name='parking_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Parking area (sqft)'),
        ),
    ]
