# Generated by Django 4.2.20 on 2026-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shown when no letterhead image is uploaded. Leave blank to use the default company name.', max_length=150)),
                ('address', models.TextField(blank=True, help_text='Shown under the name when there is no letterhead image.')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('letterhead', models.ImageField(blank=True, help_text='Header banner printed at the top of every document (PNG or JPG, max 5 MB). Best as a wide image, e.g. 2480 x 400 px, which prints at full A4 width.', upload_to='letterhead/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
