# Generated by Django 4.2.20 on 2026-09-20 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current Account'), ('SAVINGS', 'Savings Account'), ('FIXED', 'Fixed Deposit')], default='CURRENT', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['bank_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('particulars', models.CharField(max_length=300)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Book Entry',
                'verbose_name_plural': 'Cash Book Entries',
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('particulars', models.CharField(max_length=300)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='books.bankaccount')),
            ],
            options={
                'verbose_name': 'Bank Book Entry',
                'verbose_name_plural': 'Bank Book Entries',
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
    ]
