# Generated by Django 4.2.20 on 2026-09-20 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=60, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='costing.costcategory')),
            ],
            options={
                'verbose_name': 'Cost Category',
                'verbose_name_plural': 'Cost Categories',
                'ordering': ['parent_category__id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, verbose_name='Reference / Bill No.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('allocation_required', models.BooleanField(default=True, editable=False)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', editable=False, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, help_text='Leave blank for a shared project cost — it will be allocated across every apartment in the project by saleable area. Set it for a cost that belongs to one apartment only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_costs', to='projects.apartment')),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_costs', to='costing.costcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_costs', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Project Cost',
                'verbose_name_plural': 'Project Costs',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_saleable_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation_rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='projects.apartment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='projects.project')),
                ('project_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='costing.projectcost')),
            ],
            options={
                'ordering': ['apartment__floor_no', 'apartment__apartment_no'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='costing.costcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'cost_category'],
                'unique_together': {('project', 'cost_category')},
            },
        ),
    ]
