# Generated by Django 4.2.20 on 2026-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_costpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcost',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='status',
        ),
        migrations.DeleteModel(
            name='CostPayment',
        ),
    ]
