# Generated by Django 4.2.20 on 2026-09-20 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('sale_date', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Parking / Other Charges')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_sale_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('receivable_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='projects.apartment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='projects.project')),
            ],
            options={
                'verbose_name': 'Apartment Sale',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.apartmentsale')),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
